version: "3"

services:
   discovery-server:
      image: discovery-server
      build:
         context: ./discovery-server
         dockerfile: ./Dockerfile
      ports:
       - 8761:8761
        
   movie-catalog-service:
      image: movie-catalog-service
      build:
         context: ./movie-catalog-service
         dockerfile: ./Dockerfile
      ports:
       - 8081:8081
      depends_on:
       - discovery-server
       
   movie-info-service:
      image: movie-info-service
      build:
         context: ./movie-info-service
         dockerfile: ./Dockerfile
      ports:
       - 8082:8082
      depends_on:
       - discovery-server 
       
   ratings-data-service:
      image: ratings-data-service
      build:
         context: ./ratings-data-service
         dockerfile: ./Dockerfile
      ports:
       - 8083:8083
      depends_on:
       - discovery-server